### ISSUE TITLE
Occasional error in TensorNetworkFromHyperNEATSpecificationTest

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#112]
Another unit test that fails on rare occasions due to randomness:

Failed tests:   testFillWeightsFromHyperNEATNetworkAllReLU(edu.southwestern.networks.dl4j.TensorNetworkFromHyperNEATSpecificationTest): arrays first differed at element [0]; expected:<2087412.0261124107> but was:<2087412.25>

-------------------------

-------------------------------------------------------------------------------
Test set: edu.southwestern.networks.dl4j.TensorNetworkFromHyperNEATSpecificationTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.611 sec <<< FAILURE!
testFillWeightsFromHyperNEATNetworkAllReLU(edu.southwestern.networks.dl4j.TensorNetworkFromHyperNEATSpecificationTest)  Time elapsed: 0.345 sec  <<< FAILURE!
arrays first differed at element [0]; expected:<2087412.0261124107> but was:<2087412.25>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.junit.Assert.assertArrayEquals(Assert.java:365)
	at edu.southwestern.networks.dl4j.TensorNetworkFromHyperNEATSpecificationTest.testFillWeightsFromHyperNEATNetworkAllReLU(TensorNetworkFromHyperNEATSpecificationTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by DevonFulcher** [comment]
The bug can be attributed to a floating-point rounding error. Usually, the values are within an acceptable difference. I have not seen the actual JUnit assert statement fail in a about a dozen trials. The difference of the values are within a margin of .2 by the assert statement. Here are the values:

dl4j 0: 776337.125
hyperNEAT 0: 776337.0989621066

dl4j 0: 790030.4375
hyperNEAT 0: 790030.4042617836

dl4j 0: 985054.625
hyperNEAT 0: 985054.5755972519

dl4j 0: 1211274.0
hyperNEAT 0: 1211274.10119197

dl4j 0: 1127726.5
hyperNEAT 0: 1127726.5668371173

dl4j 0: 990737.3125
hyperNEAT 0: 990737.2944126449

dl4j 0: 1640626.625
hyperNEAT 0: 1640626.6659469632

dl4j 0: 977275.0
hyperNEAT 0: 977274.9448959662

dl4j 0: 795441.125
hyperNEAT 0: 795441.1821555077

dl4j 0: 980413.625
hyperNEAT 0: 980413.692945563

**Comment by schrum2** [comment]
This test has gone from having occasional errors to consistently failing. TensorNetworkFromHyperNEATSpecificationTest has now had all of its Test annotations disabled so that it won't mess up the Maven build, but I do still want this fixed.

However, note that I'm currently upgrading the version of DL4J, which may add complications. Wait a while before looking at this.

**Comment by DevonFulcher** [comment]
This JUnit test passed our recent test.
