### ISSUE TITLE
Set parameters for CustomExecutor.java from command line, via Parameters.java

### ISSUE THREAD

**Issue by Squillyprice01** [schrum2/MM-NEAT#136]
Necessary for #21

**Comment by schrum2** [comment]
Regarding the commit I just made, here is the exception I get now:

```
Exception in thread "main" java.lang.UnsupportedOperationException: TODO: implement averageGhostsEatenPerPowerPill
        at edu.southwestern.tasks.mspacman.facades.GameFacade.averageGhostsEatenPerPowerPill(GameFacade.java:2915)
        at edu.southwestern.tasks.mspacman.objectives.GhostsPerPowerPillScore.fitness(GhostsPerPowerPillScore.java:22)
        at edu.southwestern.tasks.mspacman.objectives.MsPacManObjective.score(MsPacManObjective.java:38)
```

I think this means that one complete evaluation is finishing (good news!) because I'm pretty sure that this method is called to track an "other score". To fix this, in the MsPacManTask constructor, we need to NOT use addObjective on GhostsPerPowerPillScore. In general, any time addOBjective is being used with otherScores it is safe to disable that setting, but if it is being used with objectives then we may have a problem.

**Comment by Squillyprice01** [comment]
I tried doing this but was having trouble. We can discuss it tomorrow.

**Comment by Squillyprice01** [comment]
Done
