### ISSUE TITLE
UT^2 can't handle Team Death Match Server

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#138]
Keeps crashing with this exception:

```
    Component:  Mediator[producer=WorldMessageTranslator[parser=UT2004Parser, handler=BotFSM], consumer=UT2004SyncLockableWorldView]
    Message:    MediatorWorker: Consumer exception.
    Cause:      class cz.cuni.amis.utils.exception.PogamutException: InfoMessage[TeamScoreMessage][Id = WorldObjectId[0] | Team = 0 | Score = -1 | ][Id = WorldObjectId[0] | Team = 0 | Score = -1 | ]: Can't update different class than TeamScoreMessage, got class AutoTraceRayMessage! (at cz.cuni.amis.pogamut.ut2004.communication.messages.gbinfomessages.TeamScoreMessage.update(TeamScoreMessage.java:572))
    Stacktrace:
        cz.cuni.amis.pogamut.base.component.controller.ComponentController.fatalError(ComponentController.java:513)
        cz.cuni.amis.pogamut.base.communication.mediator.impl.Mediator$Worker.run(Mediator.java:339)
        java.lang.Thread.run(Unknown Source)
    Caused by: class cz.cuni.amis.utils.exception.PogamutException: InfoMessage[TeamScoreMessage][Id = WorldObjectId[0] | Team = 0 | Score = -1 | ][Id = WorldObjectId[0] | Team = 0 | Score = -1 | ]: Can't update different class than TeamScoreMessage, got class AutoTraceRayMessage! (at cz.cuni.amis.pogamut.ut2004.communication.messages.gbinfomessages.TeamScoreMessage.update(TeamScoreMessage.java:572))
        cz.cuni.amis.pogamut.ut2004.communication.messages.gbinfomessages.TeamScoreMessage.update(TeamScoreMessage.java:572)
        cz.cuni.amis.pogamut.base3d.worldview.impl.VisionWorldView.objectUpdatedEvent(VisionWorldView.java:149)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.innerNotify(EventDrivenWorldView.java:127)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.notify(EventDrivenWorldView.java:230)
        cz.cuni.amis.pogamut.base3d.worldview.impl.BatchAwareWorldView.notify(BatchAwareWorldView.java:100)
        cz.cuni.amis.pogamut.ut2004.communication.worldview.UT2004SyncLockableWorldView.notify(UT2004SyncLockableWorldView.java:251)
        cz.cuni.amis.pogamut.base.communication.mediator.impl.Mediator$Worker.run(Mediator.java:327)
        java.lang.Thread.run(Unknown Source)
]
```

**Comment by friedmaa** [comment]
Problem found to be with ray traces, and the bot could run until it got stuck, but when it tried to use unstuck, it tried to use a ray trace, and since these were commented out, it crashed on unstuck

**Comment by friedmaa** [comment]
commented out the addRayToAutoTrace method, and any lines that called it.

**Comment by friedmaa** [comment]
tested raytraceing bot in team server, and it does work

**Comment by schrum2** [comment]
I would like an update on this issue. It looks like the simple raytracing bot does work fine in a team server, but UT^2 does not? I just want to confirm what state this issue is in.

Also, when you said you commented out addRayToAutoTrace above, what bot was that in? Does UT^2 no longer have working ray traces at all? Even in free-for-all death match?
