### ISSUE TITLE
Upgrade DL4J version to 1.0.0-beta

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#148]
I technically already did this, but it is causing problems. Specifically:
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/tools/PropertyParser

**Comment by schrum2** [comment]
I've asked the DL4J people about this here:
https://github.com/deeplearning4j/deeplearning4j/issues/5266#issuecomment-393127805

I made some further changes to the pom, which seemed to have an affect on ND4J, but this error still persists.

**Comment by schrum2** [comment]
dev branch seems fully upgraded. I went back and forth reverting some commits that I thought were questionable. In its current state, VizDoom examples with RL4J can run #25 though I won't know until tomorrow whether it crashes or performs well.

However, the upgrade introduced some new problem with the ImageNet models I was importing for my Innovation Engines. Specifically, there seems to be a missing resource file that provides the ImageNet class labels. An example of the error can be produced by running ImageNetTest to get the following:

```
Could not load ImageNet labels
org.nd4j.shade.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at org.nd4j.shade.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2648)
	at org.deeplearning4j.zoo.util.imagenet.ImageNetLabels.getLabels(ImageNetLabels.java:29)
	at org.deeplearning4j.zoo.util.BaseLabels.<init>(BaseLabels.java:22)
	at org.deeplearning4j.zoo.util.imagenet.ImageNetLabels.<init>(ImageNetLabels.java:22)
	at edu.southwestern.util.graphics.ImageNetClassification$AccessibleImageNetLabels.<init>(ImageNetClassification.java:40)
	at edu.southwestern.util.graphics.ImageNetClassification.getImageNetLabelsInstance(ImageNetClassification.java:55)
	at edu.southwestern.util.graphics.ImageNetClassification.bestLabel(ImageNetClassification.java:215)
	at org.deeplearning4j.examples.imagenet.ImageNetTest.resultsFromOne(ImageNetTest.java:164)
	at org.deeplearning4j.examples.imagenet.ImageNetTest.main(ImageNetTest.java:86)
```

**Comment by schrum2** [comment]
I've asked the DL4J team for help with this in this issue: https://github.com/deeplearning4j/deeplearning4j/issues/5402

**Comment by schrum2** [comment]
I thought I had fixed this, but the error is back. Maybe on my other machine, when the resource was read, it got cached, so that after I deleted it the code still worked despite not being accessible.

**Comment by schrum2** [comment]
I added a copy of the missing resource, which seems to work.

**Comment by schrum2** [comment]
d0e2b6e882079cf42ff28ea0a2eaa789a97c78ee
