### ISSUE TITLE
Fix Java Neural Style Transfer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#158]
Since the upgrade to DL4J 1.0.0-beta #148 the Java version of NeuralStyleTransfer written by Klevis doesn't seem to work anymore. Compare with the version in the DL4J examples to see what the problem is:

https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/styletransfer/NeuralStyleTransfer.java

However, the only big change I recall making was to add a parameter to the call to backpropGradient, and coincidentally, the DL4J people made the same code change I did. Nevertheless, the error I'm getting does include this method call in the stack trace.

Specifically, the error is the following:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot perform backprop in layer ConvolutionLayer: layer input field is not set
	at org.deeplearning4j.nn.layers.AbstractLayer.assertInputSet(AbstractLayer.java:408)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:105)
	at edu.southwestern.util.graphics.NeuralStyleTransfer.backPropagate(NeuralStyleTransfer.java:377)
	at edu.southwestern.util.graphics.NeuralStyleTransfer.backPropagateStyles(NeuralStyleTransfer.java:238)
	at edu.southwestern.util.graphics.NeuralStyleTransfer.runNeuralStyleTransfer(NeuralStyleTransfer.java:200)
	at edu.southwestern.util.graphics.NeuralStyleTransfer.main(NeuralStyleTransfer.java:225)
```

**Comment by schrum2** [comment]
Might also want to check the blog post by Klevis:
https://dzone.com/articles/java-art-generation-with-neural-style-transfer

**Comment by schrum2** [comment]
Solved. NST is still slow in Java, but it "works" now
