### ISSUE TITLE
Evolve Against Arbitrary Bots

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#167]
Currently, UT2004Task can only evolve against native bots, and bots that use the ControllerBot class. However, the code you made in MultiBotLauncher should allow us to evolve against the HunterBot, UT^2, and MirrorBot, etc.

To do this, we need to replace the call to change ControllerBot.launchBot. This code launches multiple controller bots, and returns GameDataCollector instances for those bots. Replace the code in the try with a call to MultiBotLauncher.launchMultipleBots.

For now, just make it launch ControllerBots, the way it is already doing. Once this works though, we will expand on this with other issues.

**Comment by friedmaa** [comment]
Got it to run as a java application, added explorationBot and dummyBot to the server

**Comment by friedmaa** [comment]
This is working, when using a batch file, it spawns a dummy bot and an evolving bot.

**Comment by schrum2** [comment]
This is really buggy right now, and I'm not entirely sure of the source of it. The call to MultiBotLauncher.launchMultipleBots seems to be causing problems, even though it also works much of the time. However, the problem might be running with multiple parallel threads.

For the moment, I've disabled the HunterBot as an opponent #107 because ControllerBot will crash if you try ... I was actually having trouble running MultiBotLauncher.launchMultipleBots against just the DummyBots.

Try to systematically figure out what does and doesn't work, and put there errors/exceptions in this GitHub issue. I think evolving against native bots still works, but verify this. Then try evolving against just DummyController bots. If you run into errors, then try the evolution without parallel threads turned off (is this the source of the error?).

**Comment by friedmaa** [comment]
Dummy bots crashes, it is still possible though to run native bots.
If we disable parallel threads, wouldn't that make evolving agents take hours?

**Comment by friedmaa** [comment]
`java.util.concurrent.ExecutionException: java.lang.NullPointerException3004: Empty server gets ticekt: 5

3028: Empty server gets ticekt: 4       at java.util.concurrent.FutureTask.report(Unknown Source)

3020: Past evaluate block: 1528210285881        at java.util.concurrent.FutureTask.get(Unknown Source)

Removing server with ticket: 7  at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)

3028: Past evaluate block: 1528210285882        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLamb
da.java:363)

3036: Past evaluate block: 1528210285881        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAE
xperiment.run(SinglePopulationGenerationalEAExperiment.java:215)

        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:842)3016: Past evaluate block: 1528210285881

        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1010)3004: Past evaluate block: 1528210285882
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:970)

3024: Past evaluate block: 1528210285882
Caused by: java.lang.NullPointerException(NBUTServer9)  [WARNING] 09:51:25.884 <Agent>                  Stopping agent N
BUTServer9-20@MBH118-LAB08.southwestern.edu/84c13a68-e2b1-97be-dbf6-b4437a899a82

        at edu.southwestern.tasks.ut2004.UT2004Task.oneEval(UT2004Task.java:209)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:53)
        at java.util.concurrent.FutureTask.run(Unknown Source)(NBUTServer9)  [WARNING] 09:51:25.886 <Agent>
     Component Mediator[producer=WorldMessageTranslator[parser=UT2004Parser, handler=ServerFSM], consumer=UT2004WorldVie
w] has stopped.

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)(NBUTServer9)  [WARNING] 09:51:25.887 <Agen
t>                  Component WorldMessageTranslator[parser=UT2004Parser, handler=ServerFSM] has stopped.

        at java.lang.Thread.run(Unknown Source)
(NBUTServer9)  [WARNING] 09:51:25.887 <Agent>                  Component UT2004Parser has stopped.
(NBUTServer9)  [WARNING] 09:51:25.887 <Agent>                  Component Act[serializer=StringCommandSerializer] has sto
pped.
(NBUTServer9)  [WARNING] 09:51:25.888 <Agent>                  Component SocketConnection[SocketConnectionAddress[localh
ost:3021],connected:false) has stopped.
(NBUTServer9)  [WARNING] 09:51:25.888 <Mediator>               MediatorWorker: Producer is not running, stopping the med
iator worker.
(NBUTServer9)  [WARNING] 09:51:25.888 <Mediator>               MediatorWorker: Stopped.
(NBUTServer9)  [WARNING] 09:51:25.903 <Agent>                  Component UT2004WorldView has stopped.`

**Comment by friedmaa** [comment]
changed the batch file to only run 1 thread UT2004-DummyDebug-Curse4-singlethread.bat error message
```
java.util.concurrent.ExecutionException: java.lang.NullPointerExceptionEval attempt 1

        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:363)
        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:842)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1010)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:970)[C:\SCOPE2018\UT2004\System\ucc.exe, server, DM-Curse4?game=GameBots2004.BotDeathMatch?mutator=GameBots2004.PathMarkerMutator?fraglimit=0?GoalScore=0?DoUplink=False?UplinkToGamespy=False?SendStats=False?bAllowPrivateChat=False?bAllowTaunts=False?bEnableVoiceChat=False?bAllowLocalBroadcast=False?BotServerPort=3004?ControlServerPort=3005?ObservingServerPort=3006, -port=3007]

Caused by: java.lang.NullPointerException
        at edu.southwestern.tasks.ut2004.UT2004Task.oneEval(UT2004Task.java:209)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:53)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by friedmaa** [comment]
can get bots to evolve against DummyBots when threads are NOT running in parallel

**Comment by schrum2** [comment]
This is sort of a duplicate issue with #176 . The details can be tracked in either issue thread.

**Comment by friedmaa** [comment]
created a batch file UT2004-various-Indidious, which created a free for all death match on the map insidious. It spawns in  1 evolving bot, 1 dummy bot, 1 hunter bot, and 1 mirror bot, but it had trouble finishing a generation.

**Comment by schrum2** [comment]
In what way did it have trouble? If there was an exception, then paste it here. Also, try adding UT^2.

**Comment by friedmaa** [comment]
```
java.lang.NullPointerException
        at cz.cuni.amis.pogamut.ut2004.agent.module.sensor.AgentInfo.isOnNavGraph(AgentInfo.java:1514)
        at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004GetBackToNavGraph.isOnNavGraph(UT2004GetBackToNavGraph.java:109)
        at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigateLocation(UT2004Navigation.java:596)
Bot kill interrupted
        at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigate(UT2004Navigation.java:579)
        at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigate(UT2004Navigation.java:327)
        at fr.enib.mirrorbot4.Brain.doBehavior(Brain.java:359)
        at fr.enib.mirrorbot4.Brain.execute(Brain.java:182)
        at fr.enib.mirrorbot4.MirrorBot4.logic(MirrorBot4.java:149)
        at cz.cuni.amis.pogamut.base.agent.module.LogicModule$LogicRunner.run(LogicModule.java:425)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by schrum2** [comment]
Although we experience intermittent errors, I think that all of the bots we care about are capable of being launched in an evolution server. If this is accurate, then close this issue. We'll deal with the problems of specific bots in separate issues.
