### ISSUE TITLE
Possible Issue With Evolution in Parallel in UT2004

### ISSUE THREAD

**Issue by friedmaa** [schrum2/MM-NEAT#176]
See following exception

```
java.util.concurrent.ExecutionException: PogamutException[cz.cuni.amis.utils.configuration.PropertiesManager@435887a0: Could not initialize PropertiesManager: null (caused by: null)]
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:363)
        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:842)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1010)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:970)
Caused by: PogamutException[cz.cuni.amis.utils.configuration.PropertiesManager@435887a0: Could not initialize PropertiesManager: null (caused by: null)]
        at cz.cuni.amis.utils.configuration.PropertiesManager.getProvidersList(PropertiesManager.java:69)
        at cz.cuni.amis.utils.configuration.PropertiesManager.getProperty(PropertiesManager.java:94)
        at cz.cuni.amis.pogamut.base.utils.DefaultPogamutPlatform.getProperty(DefaultPogamutPlatform.java:159)
        at cz.cuni.amis.pogamut.base.utils.logging.AgentLogger.<init>(AgentLogger.java:68)
        at cz.cuni.amis.pogamut.ut2004.factory.direct.remoteagent.UT2004ServerFactory.newAgent(UT2004ServerFactory.java:53)
        at cz.cuni.amis.pogamut.ut2004.factory.direct.remoteagent.UT2004ServerFactory.newAgent(UT2004ServerFactory.java:1)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.createAgentWithParams(AgentRunner.java:494)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.startAgentWithParams(AgentRunner.java:295)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.startAgent(AgentRunner.java:191)
        at cz.cuni.amis.pogamut.ut2004.utils.UT2004ServerRunner.startAgent(UT2004ServerRunner.java:80)
        at cz.cuni.amis.pogamut.ut2004.utils.UCCWrapper.getUTServer(UCCWrapper.java:92)
        at edu.southwestern.tasks.ut2004.UT2004Task.oneEval(UT2004Task.java:176)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:53)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at cz.cuni.amis.utils.configuration.PropertiesManager.logProvidersOrder(PropertiesManager.java:77)
        at cz.cuni.amis.utils.configuration.PropertiesManager.getProvidersList(PropertiesManager.java:66)
        ... 18 more
```

**Comment by schrum2** [comment]
I've been seeing this error a lot. I hope that this commit fixes it:
https://github.com/schrum2/MM-NEAT/commit/954ca962172421a3a873eaec7d605ef8127ddd7b
but now I'm seeing other weird exceptions.

**Comment by schrum2** [comment]
Track any errors associated with running UT2004 evolution with parallel threads here. I think the exception above has been resolved, but we still have others to deal with.

**Comment by friedmaa** [comment]
This is an issue with dummybot, because it is the only one that cannot run in parallel, native bots, hunter bots, and mirror bots can be run in parallel

**Comment by schrum2** [comment]
Is it the same PropertiesManager exception I mention above?

**Comment by schrum2** [comment]
Please provide an update on the state of this error. I feel like we narrowed down the types of bots that were causing problems, but those details need to be described in this issue.

**Comment by friedmaa** [comment]
it seemed to be fine in the UT2004-DummyDebug-Curse4.bat file, but the plain UT2004-DummyDebug.bat file crashes.

**Comment by friedmaa** [comment]
UT2 also fails to complete a generation

**Comment by friedmaa** [comment]
no exceptions, it just freezes

**Comment by schrum2** [comment]
This still seems to be an issue. The problem comes up when multiple instances of certain GameBots bots are launched simultaneously. Parallel threads seems to only be reliable when evolving against native bots. This issue will stay open, but we will ignore it for now.
