### ISSUE TITLE
GVG-AI LevelBreeder Interface: Allow for changing the game

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#198]
Hopefully you can figure this issue out before the end of the week.

Add a drop-down menu to the LevelBreeder interface that lists all of the known games. Get the list using
SPECIFIC_GAME_LEVEL_CHARS.keySet(), then transfer the contents into an ArrayList and sort the list. You can find examples of how to make a drop down box in ThreeDimensionalObjectBreederTask. Look for JComboBox. For the combo box, whenever itemStateChanged happens, change the game being used to evolve. This will require resetting the gvgaiGame parameter, and changing the values of the gameFile, fullGameFile, and gameCharData variables.

**Comment by JoeRoybal** [comment]
```
Launched
Exception in thread "Thread-2" java.lang.NullPointerException
	at gvgai.core.game.Game.getPath(Game.java:2170)
	at gvgai.ontology.sprites.npc.PathAltChaser.update(PathAltChaser.java:84)
	at gvgai.ontology.sprites.npc.RandomPathAltChaser.update(RandomPathAltChaser.java:56)
	at gvgai.core.game.ForwardModel.tick(ForwardModel.java:580)
	at gvgai.core.game.ForwardModel.advance(ForwardModel.java:596)
	at gvgai.core.game.StateObservation.advance(StateObservation.java:65)
	at gvgai.tracks.ArcadeMachine.warmUp(ArcadeMachine.java:781)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:106)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:91)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:70)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask$2.run(LevelBreederTask.java:868)
```
error produced trying to launch the game right after running the code

**Comment by JoeRoybal** [comment]
```
fullGameFile
gameCharData
spriteGroups.length = 46
spriteTypeId = 45
[gvgai.core.vgdl.SpriteGroup@6381616d, gvgai.core.vgdl.SpriteGroup@140967d4, gvgai.core.vgdl.SpriteGroup@75d40710, gvgai.core.vgdl.SpriteGroup@5acee0d4, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gvgai.core.game.Game.createAvatars(Game.java:1207)
	at gvgai.core.game.BasicGame.buildStringLevel(BasicGame.java:195)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.getLevelImage(GVGAIUtil.java:137)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask.getButtonImage(LevelBreederTask.java:850)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.getButtonImage(InteractiveEvolutionTask.java:556)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.resetButtons(InteractiveEvolutionTask.java:745)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask$1.itemStateChanged(LevelBreederTask.java:772)
	at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
	at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
	at javax.swing.JComboBox.contentsChanged(Unknown Source)
	at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
This error is for trying to switch games using the drop down menu

**Comment by JoeRoybal** [comment]
```
Removed image 1
Removed image 2
Removed image 5
Removed image 6
Removed image 7
Removed image 9
Removed image 10
Removed image 11
Removed image 12
Removed image 13
Removed image 14
Removed image 15
Removed image 16
Removed image 17
Removed image 18
Removed image 19
Removed image 20
Size of cache: 3
Starting generation: 1
Exception in thread "main" java.lang.NullPointerException
	at gvgai.core.game.ForwardModel.update(ForwardModel.java:144)
	at gvgai.core.game.Game.initForwardModel(Game.java:765)
	at gvgai.core.game.BasicGame.buildStringLevel(BasicGame.java:196)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.getLevelImage(GVGAIUtil.java:137)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask.getButtonImage(LevelBreederTask.java:850)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.getButtonImage(InteractiveEvolutionTask.java:556)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.resetButton(InteractiveEvolutionTask.java:517)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.evaluateAll(InteractiveEvolutionTask.java:591)
	at edu.southwestern.evolution.selectiveBreeding.SelectiveBreedingEA.getNextGeneration(SelectiveBreedingEA.java:125)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:842)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1010)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:970)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask.main(LevelBreederTask.java:905)
```
This error is displayed while trying to play the "base" game.

**Comment by JoeRoybal** [comment]
also, the generation is only has three pictures that show up for the "base" game and the rest are blank

**Comment by JoeRoybal** [comment]
![capture](https://user-images.githubusercontent.com/39634437/41126813-6a5192f8-6a6e-11e8-85b9-86cab3f7a599.PNG)

**Comment by schrum2** [comment]
The specific issue is that we cannot evolve the same population further in a different game. Instead, we have to completely reset the population when we change the game. However, the interface has a reset option in it already, so hopefully we can just call a function to do it? Hopefully it will be this easy.

**Comment by JoeRoybal** [comment]
where would I find this code? I a currently looking under ```Game.java``` and I see the method for ```clearInterationTerminationData()```. Also how would I call this in ```LevelBreederTask.java```

**Comment by JoeRoybal** [comment]
There is now a drop-down menu that allows you to select games and play/ evolve them without any issues
