### ISSUE TITLE
Make it easy to launch a BotPrize Server

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#205]
Make a class in the edu.southwestern.tasks.ut2004 package called BotPrizeServer that creates a server, sets the use of the BotPrize mod to true (which of course depends on using the right version of GameBots), and puts one copy of MirrorBot and one copy of UT^2 onto the server. All debugging visualizations should be turned off, though this partly depends on the configuration of GameBots.ini.

I think this can be accomplished by calling the evaluateMultipleGenotypes method of UT2004Task with an empty array of Genotypes (length = 0). You will also need to call Parameters.initializeParameters (or something similar) and then manually set the relevant params, like the number of UT^2 and MirrorBot instances. Set the eval time to 15 minutes as well.

We want to have a situation where you can right click the file and run-as to get a BotPrize server that humans can easily log into (something you've tried to do several times already)

**Comment by schrum2** [comment]
Before starting #209 take a shot at this one, as hopefully it will be fairly easy, and will make it easy for us to test the game out as humans vs the bots.

**Comment by friedmaa** [comment]
Is there an already existing server launch file that I can model this one on?

**Comment by schrum2** [comment]
No, there is not. It's basically a main method that calls UT2004Task.evaluateMultipleGenotypes, but you have to set up all of the parameters first

**Comment by friedmaa** [comment]
```
BUG found
java.lang.NullPointerException
	at cz.cuni.amis.pogamut.ut2004.agent.module.sensor.AgentInfo.isOnNavGraph(AgentInfo.java:1514)
	at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004GetBackToNavGraph.isOnNavGraph(UT2004GetBackToNavGraph.java:109)
	at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigateLocation(UT2004Navigation.java:596)
	at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigate(UT2004Navigation.java:579)
	at cz.cuni.amis.pogamut.ut2004.agent.navigation.UT2004Navigation.navigate(UT2004Navigation.java:327)
	at fr.enib.mirrorbot4.Brain.doBehavior(Brain.java:359)
	at fr.enib.mirrorbot4.Brain.execute(Brain.java:182)
	at fr.enib.mirrorbot4.MirrorBot4.logic(MirrorBot4.java:149)
	at cz.cuni.amis.pogamut.base.agent.module.LogicModule$LogicRunner.run(LogicModule.java:425)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by friedmaa** [comment]
Second exception that crashes
```
BUG found
java.lang.NullPointerException
(UT^2)        [WARNING] 11:17:22.019 <FloydWarshallMap125>    Log level set to OFF.
(UT^2)        [WARNING] 11:17:22.019 <FloydWarshallMap124>    Log level set to OFF.
	at cz.cuni.amis.pogamut.ut2004.agent.module.sensor.WeaponPrefs.getWeaponPreference(WeaponPrefs.java:225)
	at cz.cuni.amis.pogamut.ut2004.agent.module.sensor.WeaponPrefs.getWeaponPreference(WeaponPrefs.java:324)
	at fr.enib.mirrorbot4.ShootingData.step(ShootingData.java:82)
	at fr.enib.mirrorbot4.Brain.doBehavior(Brain.java:391)
	at fr.enib.mirrorbot4.Brain.execute(Brain.java:182)
	at fr.enib.mirrorbot4.MirrorBot4.logic(MirrorBot4.java:149)
	at cz.cuni.amis.pogamut.base.agent.module.LogicModule$LogicRunner.run(LogicModule.java:425)
	at java.lang.Thread.run(Thread.java:748)
Empty index!
Empty index!
```
