### ISSUE TITLE
Pacman with parallel evaluation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#213]
Try pacman with the parallelThreads setting and see if it works. If any global variables are used in weird ways, then it will not work, but hopefully it will. Do some benchmarking and make sure that results with multiple threads are similar in terms of fitness to results without. They should also be faster.

You can ask @friedmaa how to use parallel threads.

**Comment by Squillyprice01** [comment]
![screenshot 13](https://user-images.githubusercontent.com/15305479/41245783-a253754c-6d6e-11e8-8444-c32e965fbae5.png)

**Comment by Squillyprice01** [comment]
The results of using parallel threads! I can debug and see if these are an easy fix before giving up on it.

**Comment by schrum2** [comment]
Try turning assertions on to see if this helps you track the issue down

**Comment by Squillyprice01** [comment]
Im not entirely sure what is going on but running a test with parallel evaluations causes errors in other tests that were already running.

**Comment by schrum2** [comment]
It turns out that even with the old version of pacman the parallel threads do not work. With assertions on, I get this error:
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: Picked invalid direction 2 given neighbors [-1, 982, -1, 980]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
	at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:363)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:842)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1010)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:970)
Caused by: java.lang.AssertionError: Picked invalid direction 2 given neighbors [-1, 982, -1, 980]
	at edu.southwestern.tasks.mspacman.facades.GameFacade.getTargetInDirFromNew(GameFacade.java:1526)
	at edu.southwestern.tasks.mspacman.facades.GameFacade.getTargetInDir(GameFacade.java:1493)
	at edu.southwestern.tasks.mspacman.facades.GameFacade.getTargetInDir(GameFacade.java:1466)
	at edu.southwestern.tasks.mspacman.sensors.directional.reachfirst.VariableDirectionCloserToTargetThanThreatGhostBlock.canReachClosestTargetSafelyInDirection(VariableDirectionCloserToTargetThanThreatGhostBlock.java:111)
	at edu.southwestern.tasks.mspacman.sensors.directional.VariableDirectionCountJunctionOptionsBlock.getValue(VariableDirectionCountJunctionOptionsBlock.java:39)
	at edu.southwestern.tasks.mspacman.sensors.directional.VariableDirectionBlock.incorporateSensors(VariableDirectionBlock.java:28)
	at edu.southwestern.tasks.mspacman.sensors.BlockLoadedInputOutputMediator.getInputs(BlockLoadedInputOutputMediator.java:41)
	at edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNCheckEachDirectionPacManController.getDirectionPreferences(NNCheckEachDirectionPacManController.java:187)
	at edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNDirectionalPacManController.getDirection(NNDirectionalPacManController.java:33)
	at edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNPacManController.getAction(NNPacManController.java:131)
	at edu.southwestern.tasks.mspacman.agentcontroller.pacman.NNPacManController.getAction(NNPacManController.java:75)
	at oldpacman.controllers.NewPacManController.getMove(NewPacManController.java:56)
	at oldpacman.controllers.NewPacManController.getMove(NewPacManController.java:1)
	at oldpacman.Executor.runExperiment(Executor.java:179)
	at edu.southwestern.tasks.mspacman.facades.ExecutorFacade.runExperiment(ExecutorFacade.java:77)
	at edu.southwestern.tasks.mspacman.MsPacManTask.agentEval(MsPacManTask.java:606)
	at edu.southwestern.tasks.mspacman.MsPacManTask.oneEval(MsPacManTask.java:545)
	at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
	at edu.southwestern.tasks.mspacman.MsPacManTask.evaluate(MsPacManTask.java:524)
	at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
	at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schrum2** [comment]
It would be nice to fix this, but it is a low priority issue for now.

**Comment by schrum2** [comment]
Making old experiments in PacMan run a bit faster is not a priority worth pursuing
