### ISSUE TITLE
Exceptions in AnimationBreeder

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#220]
```
Exception in thread "Thread-383" Exception in thread "Thread-384" java.lang.IndexOutOfBoundsException: Index: 11, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at edu.southwestern.tasks.interactive.animationbreeder.AnimationBreederTask$AnimationThread.run(AnimationBreederTask.java:83)
java.lang.IndexOutOfBoundsException: Index: 10, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at edu.southwestern.tasks.interactive.animationbreeder.AnimationBreederTask$AnimationThread.run(AnimationBreederTask.java:83)
Exception in thread "Thread-382" java.lang.IndexOutOfBoundsException: Index: 9, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at edu.southwestern.tasks.interactive.animationbreeder.AnimationBreederTask$AnimationThread.run(AnimationBreederTask.java:83)
```

**Comment by schrum2** [comment]
This bug is really annoying because it doesn't seem to cause any problems. All buttons seem to animate fine without problems despite the exceptions (which do not always happen). However, every attempt I'm made to fix the issue either doesn't work or breaks animations.
