### ISSUE TITLE
Apply RL4J to VizDoom

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#25]
Use the RL4J code on VizDoom. This supposedly already works, so I can look at the RL4J code to get more inspiration, but I will use my existing code that actually successfully runs VizDoom.

**Comment by schrum2** [comment]
My version of VizDoom is older that then one this code is designed for. Despite that, I was able to make it work, but a few small issues are lingering, and I wonder if it is because of the version difference. I could try upgrading VizDoom. The instructions on this site should be able to compile it from source, though I had trouble with my first attempt:
https://github.com/rubenfiszel/rl4j-examples

**Comment by schrum2** [comment]
Just asked for help with VizDoom crashing in this issue: https://github.com/deeplearning4j/rl4j/issues/64

However, in the meantime, I should see if I can load the saved model and resume further training, as this might be a way to get around the crashing in the short term.

**Comment by schrum2** [comment]
Things seem to be as well as they were before, despite switching back to 0.9.1 versions of all DL4J jars.

Need to make sure model loading still works, and then need to focus on loading the model to resume further training after a crash. I also wonder if exception handling might be a possibility.

**Comment by schrum2** [comment]
I need to update my version of DL4J and see if this is still broken. They are currently tracking this issue in this thread: https://github.com/deeplearning4j/deeplearning4j/issues/5266

**Comment by schrum2** [comment]
Run and see if you can recreate my bug. It is possible that the new version of DL4J will fix this for us. Otherwise, you can/should followup with the DL4J people in the thread I refer to above.

**Comment by schrum2** [comment]
I ran org.deeplearning4j.examples.rl4j.Doom overnight and ended up with the same bug. Here is the stack trace and error message:

21:06:44.580 [main] ERROR org.deeplearning4j.rl4j.learning.sync.SyncLearning - Training failed.
java.lang.NullPointerException: null
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:50)
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:38)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:45)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:52)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.trainStep(QLearningDiscrete.java:159)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:91)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:38)
	at org.deeplearning4j.examples.rl4j.Doom.doomLearn(Doom.java:101)
	at org.deeplearning4j.examples.rl4j.Doom.main(Doom.java:79)
java.lang.NullPointerException
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:50)
	at org.deeplearning4j.rl4j.learning.sync.Transition.dup(Transition.java:38)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:45)
	at org.deeplearning4j.rl4j.learning.sync.ExpReplay.getBatch(ExpReplay.java:52)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.trainStep(QLearningDiscrete.java:159)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:91)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:38)
	at org.deeplearning4j.examples.rl4j.Doom.doomLearn(Doom.java:101)
	at org.deeplearning4j.examples.rl4j.Doom.main(Doom.java:79)
 size:  1029
[libx264 @ 000000006b8b8aa0] consecutive B-frames:  5.9%  6.3% 12.2% 75.7%
[libx264 @ 000000006b8b8aa0] mb I  I16..4:  1.8% 76.3% 21.9%
[libx264 @ 000000006b8b8aa0] mb P  I16..4:  0.9%  6.8%  1.0%  P16..4: 45.2%  4.9%  2.2%  0.0%  0.0%    skip:39.0%
[libx264 @ 000000006b8b8aa0] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8: 36.4%  0.9%  0.1%  direct: 0.2%  skip:62.3%  L0:49.5% L1:50.3% BI: 0.2%
[libx264 @ 000000006b8b8aa0] 8x8 transform intra:77.2% inter:85.2%
[libx264 @ 000000006b8b8aa0] coded y,uvDC,uvAC intra: 63.3% 47.0% 21.0% inter: 5.7% 3.0% 0.2%
[libx264 @ 000000006b8b8aa0] i16 v,h,dc,p: 53% 18% 15% 13%
[libx264 @ 000000006b8b8aa0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 11% 25%  7%  8%  8% 10%  6%  7%
[libx264 @ 000000006b8b8aa0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 22% 20%  5%  6%  4%  6%  3%  3%
[libx264 @ 000000006b8b8aa0] i8c dc,h,v,p: 68% 13% 18%  2%
[libx264 @ 000000006b8b8aa0] Weighted P-Frames: Y:2.9% UV:2.9%
[libx264 @ 000000006b8b8aa0] ref P L0: 64.2% 18.6% 11.9%  5.1%  0.1%
[libx264 @ 000000006b8b8aa0] ref B L0: 90.7%  7.7%  1.7%
[libx264 @ 000000006b8b8aa0] ref B L1: 96.2%  3.8%
[libx264 @ 000000006b8b8aa0] kb/s:551.74
[libx264 @ 000000005c716960] -qscale is ignored, -crf is recommended.
[libx264 @ 000000005c716960] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 000000005c716960] profile High, level 3.1
[libx264 @ 000000005c716960] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=30.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\schrum2\rl4j-data\1/video/video-807-70345.mp4':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (Constrained Baseline) ([33][0][0][0] / 0x0021), yuv420p, 800x600, q=2-31, 400 kb/s, 15360 tbn
[libx264 @ 000000005c716960] frame I:2     Avg QP:27.81  size: 25424
[libx264 @ 000000005c716960] frame P:155   Avg QP:31.96  size:  3855
[libx264 @ 000000005c716960] frame B:240   Avg QP:34.94  size:  1100
[libx264 @ 000000005c716960] consecutive B-frames: 13.9% 10.6% 18.1% 57.4%
[libx264 @ 000000005c716960] mb I  I16..4:  3.3% 77.1% 19.6%
[libx264 @ 000000005c716960] mb P  I16..4:  0.7%  4.4%  0.6%  P16..4: 45.9%  3.9%  1.9%  0.0%  0.0%    skip:42.6%
[libx264 @ 000000005c716960] mb B  I16..4:  0.1%  0.2%  0.0%  B16..8: 36.2%  0.9%  0.1%  direct: 0.2%  skip:62.4%  L0:52.2% L1:47.7% BI: 0.2%
[libx264 @ 000000005c716960] 8x8 transform intra:75.6% inter:86.9%
[libx264 @ 000000005c716960] coded y,uvDC,uvAC intra: 61.6% 47.3% 20.7% inter: 6.1% 3.4% 0.3%
[libx264 @ 000000005c716960] i16 v,h,dc,p: 49% 23% 15% 13%
[libx264 @ 000000005c716960] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 12% 26%  7%  8%  7%  9%  6%  7%
[libx264 @ 000000005c716960] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 23% 20%  5%  5%  4%  5%  3%  3%
[libx264 @ 000000005c716960] i8c dc,h,v,p: 68% 12% 18%  2%
[libx264 @ 000000005c716960] Weighted P-Frames: Y:4.5% UV:3.9%
[libx264 @ 000000005c716960] ref P L0: 66.2% 18.9% 10.1%  4.6%  0.2%
[libx264 @ 000000005c716960] ref B L0: 90.7%  8.0%  1.3%
[libx264 @ 000000005c716960] ref B L1: 97.7%  2.3%
[libx264 @ 000000005c716960] kb/s:551.59

**Comment by schrum2** [comment]
Same crash happens after the DL4J upgrade #148 

However, the getNeuralNetwork method mentioned in this issue ( https://github.com/deeplearning4j/rl4j/issues/69 ) should now be accessible, so try resuming the training.

**Comment by schrum2** [comment]
I am able to load the saved model and keep training! Maybe I can actually get good performance now. I should still verify that loading the previous model actually starts the learning off at a better place though, but looking at the rewards/return more closely.

**Comment by schrum2** [comment]
Still not getting good performance, even after re-loading the model across several days of training. However, I should verify that the loaded model is about at the level it was before saving. Overall, there is a problem here of not really tracking performance in a clear enough way.

Regardless, this issue is now being tracked on the DL4J side in this location:
https://github.com/deeplearning4j/deeplearning4j/issues/5266

**Comment by schrum2** [comment]
The DL4J team needs me to run ALE to see if the problem is specific to VizDoom, or a broader issue with their code. I've been unable to find time to do this, but if I ever return to this issue, the place to start is by installing ALE.

**Comment by schrum2** [comment]
After #26 you can look at this.

**Comment by schrum2** [comment]
Gave up on VizDoom and completely removed it #589. Therefore, close this issue too.
