### ISSUE TITLE
Remove utNativeBotSkill

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#256]
After looking around, it seems that this value can only be set via the INI files and not by launching the game from the command line or any other way that I can find. This means that the command line parameter for this is quite misleading, and should be removed entirely.

Remove this parameter, and all code that uses is. In some places, an array of bot skill levels is used to determine the skills of all the native bots that are launched. Replace such parameters with an integer that is simply the number of native bots to add. In fact, switching the code in this way will make it easier to configure the number of native bots in a match ... if there is not already a parameter for this, then make one.

**Comment by schrum2** [comment]
The utNativeBotSkill param is gone, so what is left to do for this issue? Why reopen?

**Comment by friedmaa** [comment]
Because after closing, all the errors popped up, so I reopened until they are dealt with

**Comment by friedmaa** [comment]
exception when attempted to run from a batch file:

```
Evaluation failed: repeat: 3024 at java.util.concurrent.FutureTask.report(Unknown Source)

(UCC)      [INFO]    11:41:17.588 <Wrapper>           ID0 GB server on. at java.util.concurrent.FutureTask.get(Unknown Source)

(UCC)      [INFO]    11:41:17.592 <Wrapper>           ID0 BotServerPort:3028 ControlServerPort:3029 ObservingServerPort:3030    at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)

        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:370)Evaluation failed: repeat: 3028

        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:850)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1018)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:978)
Caused by: PogamutException[cz.cuni.amis.pogamut.ut2004.utils.UT2004ServerRunner@32ed175c: Agent's can't be started: null (caused by: null)]
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.startAgentWithParams(AgentRunner.java:327)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.startAgent(AgentRunner.java:191)
        at cz.cuni.amis.pogamut.ut2004.utils.UT2004ServerRunner.startAgent(UT2004ServerRunner.java:80)
        at cz.cuni.amis.pogamut.ut2004.utils.UCCWrapper.getUTServer(UCCWrapper.java:92)
        at edu.southwestern.tasks.ut2004.UT2004Task.evaluateMultipleGenotypes(UT2004Task.java:178)
        at edu.southwestern.tasks.ut2004.UT2004ManyVsNativeBotsTeamDeathMatchTask.oneEval(UT2004ManyVsNativeBotsTeamDeathMatchTask.java:96)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:53)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at cz.cuni.amis.utils.configuration.PropertiesManager.getProperty(PropertiesManager.java:94)
        at cz.cuni.amis.pogamut.base.utils.DefaultPogamutPlatform.getProperty(DefaultPogamutPlatform.java:159)
        at cz.cuni.amis.pogamut.base.utils.logging.AgentLogger.<init>(AgentLogger.java:68)
        at cz.cuni.amis.pogamut.ut2004.factory.direct.remoteagent.UT2004ServerFactory.newAgent(UT2004ServerFactory.java:53)
        at cz.cuni.amis.pogamut.ut2004.factory.direct.remoteagent.UT2004ServerFactory.newAgent(UT2004ServerFactory.java:1)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.createAgentWithParams(AgentRunner.java:494)
        at cz.cuni.amis.pogamut.base.agent.utils.runner.impl.AgentRunner.startAgentWithParams(AgentRunner.java:295)
```
