### ISSUE TITLE
Exception in Mario Level CPPN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#287]
CPPN probably creates such a weird level that A* can't handle. Hasn't happened in Mario GAN #283 
```
Exception in thread "main" java.lang.NullPointerException
        at competition.cig.robinbaumgarten.astar.AStarSimulator.search(AStarSimulator.java:267)
        at competition.cig.robinbaumgarten.astar.AStarSimulator.optimise(AStarSimulator.java:570)
        at competition.cig.robinbaumgarten.AStarAgent.getAction(AStarAgent.java:102)
        at ch.idsia.mario.engine.MarioComponent.run1(MarioComponent.java:184)
        at ch.idsia.mario.simulation.BasicSimulator.simulateOneLevel(BasicSimulator.java:69)
        at ch.idsia.tools.Evaluator.evaluate(Evaluator.java:123)
        at edu.southwestern.tasks.mario.level.MarioLevelUtil.agentPlaysLevel(MarioLevelUtil.java:296)
        at edu.southwestern.tasks.mario.MarioLevelTask.oneEval(MarioLevelTask.java:92)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:370)
        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:867)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1035)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:995)
```

**Comment by schrum2** [comment]
Not important enough to pursue further.
