### ISSUE TITLE
Error resuming evolution after playing a dungeon

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#362]
If I evolve rooms using the Zelda GAN for a while, and then click Dungeonize, it will let me play the level. However, after I beat the level if I try to evolve the selected rooms further, the code crashes.

I suspect that when creating the dungeon you are turning some sort of parameter associated with saving files to true, and then when the evolution resumes it is looking to save files in a directory that doesn't exist.

```
java.io.FileNotFoundException: \0\bestObjectives\gen2_keptGenotypesIn0.xml (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.FileWriter.<init>(FileWriter.java:63)Could not write '23:[0.3377209272639704, 0.6073350789607563, 0.3154227864574829, 0.024472129835244494, 0.45100850261544956, 0.369134315501327, 0.4638377596597093, 0.17724271181295093, 0.6761231545253681, 0.7155724849913587]' to '/0/bestObjectives/gen2_genotypes0.txt'

	at wox.serial.Easy.save(Easy.java:25)
	at edu.southwestern.util.PopulationUtil.saveCurrentGen(PopulationUtil.java:183)
	at edu.southwestern.evolution.selectiveBreeding.SelectiveBreedingEA.getNextGeneration(SelectiveBreedingEA.java:169)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:878)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1078)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1038)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.main(ZeldaGANLevelBreederTask.java:273)
java.io.FileNotFoundException: \0\bestObjectives\gen2_genotypes0.txt (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at edu.southwestern.util.file.FileUtilities.simpleFileWrite(FileUtilities.java:60)
	at edu.southwestern.util.PopulationUtil.saveCurrentGen(PopulationUtil.java:184)
	at edu.southwestern.evolution.selectiveBreeding.SelectiveBreedingEA.getNextGeneration(SelectiveBreedingEA.java:169)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:878)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1078)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1038)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.main(ZeldaGANLevelBreederTask.java:273)
Traceback (most recent call last):
  File ".\src\main\python\GAN\generator_ws.py", line 138, in <module>
    lv = numpy.array(json.loads(line))
  File "C:\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jakeryang** [comment]
Fixed, problem was that I was reinitializing parameters to play the dungeon.
