### ISSUE TITLE
Error output from graph level with original rooms

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#402]
I ran ZeldaStudy.bat 0 and when the level using the graph grammar with original Zelda rooms ran, there was a bunch of error output to the console (pasted below). However, the level ran fine without any problem ... we still should remove this output though. Are these files not in the repo? Do they need to be?

```
D:\GitHub\MM-NEAT>java -jar target/MM-NEAT-0.0.1-SNAPSHOT.jar zeldaType:generated randomSeed:0 zeldaLevelLoader:edu.southwestern.tasks.gvgai.zelda.level.OriginalLoader  1>batch/Experiments-2019-ZeldaGAN/Subject-0/Subject-0-GeneratedOriginal.txt
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_0.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_4.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:84)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_5.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_8.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_12.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_13.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:84)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_14.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_15.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:79)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: D:\GitHub\MM-NEAT\data\VGLC\Zelda\GraphDOTs\graph_46.dot (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at edu.southwestern.util.datastructures.GraphUtil.saveGrammarGraph(GraphUtil.java:26)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:149)
        at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:84)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:59)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
java.io.FileNotFoundException: File does not exist: data\VGLC\Zelda\Dungeons
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2275)
        at edu.southwestern.tasks.gvgai.zelda.dungeon.DungeonUtil.recursiveGenerateDungeon(DungeonUtil.java:636)
        at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:61)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1056)
```

**Comment by schrum2** [comment]
I think this is resolved.
