### ISSUE TITLE
Fix non-determinism

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#415]
The lack of determinism across machines and between Maven and Eclipse is making it almost impossible to troubleshoot the problems we are having. We need to find a way of fixing this.

There are still randomized Strings being used in HashMaps I believe, even though I removed at least two sources of random String generation (I think). Where else are they generated?

**Comment by schrum2** [comment]
Comparing between Eclipse and Maven. Somehow the size of the rule set changes in applyRule. Here is the Eclipse output:
```
int: 0 (out of 1)
java.lang.IllegalArgumentException
	at edu.southwestern.util.random.RandomNumbers$1.nextInt(RandomNumbers.java:45)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:101)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:75)
	at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:76)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1057)
int: 1 (out of 2)
java.lang.IllegalArgumentException
	at edu.southwestern.util.random.RandomNumbers$1.nextInt(RandomNumbers.java:45)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:101)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:80)
	at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:76)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1057)
```
and the Maven output
```
int: 0 (out of 1)
java.lang.IllegalArgumentException
	at edu.southwestern.util.random.RandomNumbers$1.nextInt(RandomNumbers.java:45)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:101)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:75)
	at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:76)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1057)
int: 0 (out of 1)
java.lang.IllegalArgumentException
	at edu.southwestern.util.random.RandomNumbers$1.nextInt(RandomNumbers.java:45)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRule(GraphRuleManager.java:101)
	at edu.southwestern.tasks.gvgai.zelda.level.GraphRuleManager.applyRules(GraphRuleManager.java:75)
	at edu.southwestern.tasks.gvgai.zelda.study.HumanSubjectStudy2019Zelda.runTrial(HumanSubjectStudy2019Zelda.java:76)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1057)
```
It generated a different random number, but this was because it was generating the number under a max of 1 instead of 2.

**Comment by schrum2** [comment]
I'm reasonably certain we fixed this by using .equals instead of == on that String. I'm going to close this for now. The Eclipse and Maven builds on any one machine are definitely in sync now, and it seems that levels will be consistent across machines as well.
