### ISSUE TITLE
Different MAP Elites Bins for Mario

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#442]
CPPN2GAN Mario levels have too much repetition. Can this be solved with better MAP Elites binning? As in #441 we could use a Set for each level segment and have a binning dimension that encourages different numbers of unique level segments.

**Comment by schrum2** [comment]
Zelda is the first priority, but once you get experience with #441 you should do the same thing for Mario.

**Comment by schrum2** [comment]
I think it makes sense to only have one person get real deep in understanding MAP Elites, so I'm transferring this one to @cappsb too. In Mario, one of the dimensions should be the number of unique segments. In this case, you can take the whole List<List<Integer>> representation ... no need to crop anything.

Not sure what the other dimensions should be, but it would make sense to have two more. We could reuse some of the existing ones, but I don't really like them. Still, we need a starting point, so define a bin labeling scheme that uses the same Decoration and Negative Space calculations, and makes the third bin be the number of distinct segments. We might make more labeling schemes later.

**Comment by schrum2** [comment]
I did some work on this. I changed the batch files a bit, uncovered an error related to file paths (this was due to another change I made), but still eventually came up with another error. When I run the command:
`MarioMAPElites-CPPN.bat 0`
It leads to a crash with the following stack trace:
```
Save archive images
mariolevels/CPPN2GAN0\archive\DistinctSegments[9]NS[60-70]Leniency[-20--10]_343.00000_1.png
Save image: mariolevels/CPPN2GAN0\archive\DistinctSegments[9]NS[60-70]Leniency[-20--10]_343.00000_1.png
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:75)
        at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:56)
        at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:43)
        at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:28)
        at edu.southwestern.MMNEAT.MMNEAT.loadClasses(MMNEAT.java:819)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:905)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1132)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1092)
Caused by: java.lang.IndexOutOfBoundsException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Saved object to mariolevels/CPPN2GAN0\archive\DistinctSegments[9]NS[60-70]Leniency[-20--10]-elite.xml   at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)

        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
        at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
        at java.util.stream.IntPipeline.count(IntPipeline.java:429)
        at edu.southwestern.evolution.mapelites.Archive.add(Archive.java:130)
        at edu.southwestern.evolution.mapelites.MAPElites.initialize(MAPElites.java:179)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:26)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:21)
        ... 12 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1000, Size: 1000
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at edu.southwestern.evolution.mapelites.Archive.lambda$0(Archive.java:100)
        at java.util.stream.IntPipeline$9$1.accept(IntPipeline.java:343)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.reflect.InvocationTargetException
```

I think the most important part of this is
`java.lang.IndexOutOfBoundsException: Index: 1000, Size: 1000`
which I think is directly related to the binning scheme some how.

**Comment by cappsb** [comment]
@schrum2 I think it's done but required better testing

**Comment by schrum2** [comment]
I agree that this works, though looking at it now, I want to have yet another MAP Elites bin scheme for Mario. This new one is fine and should be kept. Currently, the bin dimensions are distinct chunks, sum of negative space scores across all chunks, and sum of leniency scores across all chunks.

Make a new binning scheme. It should still have a dimension for distinct chunks. The next dimension should be for decoration and negative space (not using leniency any more). However, instead of using the sumStatScore, use the alternatingStatScore.

Note that while leniency scores could be positive or negative, decoration and negative space can only be positive. Also, I'm not sure what range of values these scores will cover, so the scaling of the bins will likely need to be different, but either way we want to scale them into 10 bins in the decoration and negative space dimensions.

While doing this, please refactor the code in MarioLevelTask to remove as much duplicate/repeated code as possible. In fact, this should be done first. Currently, the `if(((MAPElites<T>) MMNEAT.ea).getBinLabelsClass() instanceof MarioMAPElitesDecorNSAndLeniencyBinLabels) ` case and the `else if(((MAPElites<T>) MMNEAT.ea).getBinLabelsClass() instanceof MarioMAPElitesDistinctRoomsNSAndLeniencyBinLabels)` case have a lot of similarity, and you will be adding yet a third case in a moment. Therefore, code that is identical in both cases should either be moved before the start of the if/else-if, after it, or extracted into a private method so that the code appears once, and the method can be called in both cases. This refactoring will reduce the amount of code unique to each case, and also make it easier to create a new, third case for a different binning scheme.

**Comment by cappsb** [comment]
I multiplied the bin index for decorationBinIndex by ten and it seems to have a pretty even spread @schrum2

**Comment by schrum2** [comment]
Have this preliminary heat map:
![image](https://user-images.githubusercontent.com/8397236/83555229-969abf00-a4d3-11ea-8a54-4ab36d457f19.png)
However, the bins are too full, which makes me thing that we may have too many solutions outside the range. Bin dimensions for #442 probably need to change

**Comment by schrum2** [comment]
This new scale mostly keeps the values in bounds of the bins:
![image](https://user-images.githubusercontent.com/8397236/83601588-7bad6680-a536-11ea-992c-70f9ab1b8927.png)
Also, we notice the obvious fact that if there is only 1 distinct segment, there can't be any alternation in decoration of space coverage between adjacent segments. #500
