### ISSUE TITLE
Null Pointer Exception given certain rule set

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#463]
Using the following rules in MoreInterestingGrammarRules:
rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.START_S, ZeldaGrammar.KEY_S);
		rule.grammar().setStart(ZeldaGrammar.START);
		rule.grammar().addNodeToStart(ZeldaGrammar.KEY);
		graphRules.add(rule);

		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.ENEMY_S, ZeldaGrammar.KEY_S);
		rule.grammar().setStart(ZeldaGrammar.ENEMY);
		rule.grammar().addNodeToStart(ZeldaGrammar.KEY);
		graphRules.add(rule);
		
		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.KEY_S, ZeldaGrammar.LOCK_S);
		rule.grammar().setStart(ZeldaGrammar.KEY);
		rule.grammar().addNodeToStart(ZeldaGrammar.LOCK);
		graphRules.add(rule);

		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.START_S, ZeldaGrammar.RAFT_S);
		rule.grammar().setStart(ZeldaGrammar.START);
		rule.grammar().setEnd(ZeldaGrammar.RAFT);
		graphRules.add(rule);
		
		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.KEY_S, ZeldaGrammar.RAFT_S);
		rule.grammar().setStart(ZeldaGrammar.KEY);
		rule.grammar().setEnd(ZeldaGrammar.RAFT);
		graphRules.add(rule);
		
		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.ENEMY_S, ZeldaGrammar.RAFT_S);
		rule.grammar().setStart(ZeldaGrammar.ENEMY);
		rule.grammar().addNodeToStart(ZeldaGrammar.RAFT);
		rule.grammar().setEnd(ZeldaGrammar.ENEMY);
		graphRules.add(rule);

	        rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.RAFT_S);
		rule.grammar().setStart(ZeldaGrammar.RAFT);
		graphRules.add(rule);
		
		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.LOCK_S);
		rule.grammar().setStart(ZeldaGrammar.LOCK);
		graphRules.add(rule);
		
		rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.LOCK_S, ZeldaGrammar.ENEMY_S);
		rule.grammar().setStart(ZeldaGrammar.LOCK);
		rule.grammar().setEnd(ZeldaGrammar.ENEMY);

and the following backbone:
initialList.add(ZeldaGrammar.START_S);
		initialList.add(ZeldaGrammar.ENEMY_S);
		initialList.add(ZeldaGrammar.KEY_S);
		initialList.add(ZeldaGrammar.LOCK_S);
		initialList.add(ZeldaGrammar.ENEMY_S);
		initialList.add(ZeldaGrammar.RAFT_S);
		initialList.add(ZeldaGrammar.KEY_S);
		initialList.add(ZeldaGrammar.PUZZLE_S);
		initialList.add(ZeldaGrammar.LOCK_S);
		initialList.add(ZeldaGrammar.ENEMY_S);
		initialList.add(ZeldaGrammar.TREASURE);
you get a null pointer exception. Why?

**Comment by cappsb** [comment]
found out about this while working on #452

**Comment by cappsb** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/63438571/81960108-110fa780-95d6-11ea-9be0-780d599c9f39.png)

**Comment by schrum2** [comment]
It seems as though it is looking for a room named "null". I know that all rooms get assigned randomized string labels, like IVCR, etc. So, the question to figure out is: Is there a room that is not receiving a proper name (it's name really is "null") or is the code looking for the name "null" when it should be looking for something else.

If you can't track down the exact place in the code to look at yet, then here is something you should try in order to understand the error better: Make a brand new grammar, and try to develop a minimal, simplistic (ie boring) set of rules that results in the error. It might be the case that the rules have to be "interesting" (whatever that means) in order for the error to occur. In any case, you need to figure out exactly what types of rules are problematic and why.

**Comment by cappsb** [comment]
got a new null pointer. I'll go make a basic set of rules as see what's wrong

![image](https://user-images.githubusercontent.com/63438571/81977950-6658b280-95f0-11ea-8c62-0816efac0b84.png)

**Comment by cappsb** [comment]
Changing seed sometimes fixes it

**Comment by cappsb** [comment]
#445 

Here's why the null pointer happens:
1. Unable to generate in 2D
 - sometimes different rules "stack" on top of each other, creating a problem in the generation of the dungeon. When this happens, it happens either because of faulty rules or an incompatible backbone combination. The former is fixed by simply deleting one of the addNodeToStart/addNodeBetween to make for a slimmer build. The latter is generally caused by a huge backbone (15-30 entries) and is harder to track down.
2. Nowhere to go
 - even though there may be a rule for any given combination, that doesn't necessarily mean that the computer knows to use the correct rule to lead to a solution. Whenever this happens, just change the terminal 'end' in the ruleset to non-terminal to give the generator a bit of a kick-start.

Here's how to find out what to do to fix it:

go to MM-NEAT\batch\Experiments-2020-CEC-ZeldaGAN
go to the subject directory based on your seed
open DungeonGraph_OriginalLoader.dot
go to http://www.webgraphviz.com/ and paste the contents of the .dot file to generate the graph
look at the graph to see if something strange is happening.


If the graph has more than three nodes on the same level (it shouldn't now that I've changed the rules), then change the rules to prevent this **note sometimes this happens when two parallel branches interfere with one another, hard to avoid/track down!**

if the graph does not have "t" (for treasure/triforce), then it means that the generator got stuck and you need to fix using 2. (above).

I believe I have fixed (most, if not all of) the null pointers associated with any combination of fewer than ten backbone parameters. I cannot check every combination greater than ten, but sometimes the generator creates a dungeon with too many parallel branches that interfere (see 1.)


General rules for creating rules!
When rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.TYPE_S, ZeldaGrammar.TYPE_S);
then using addNodeToStart and addNodeBetween are effectively the same when it comes to translating it to a graph, so don't use more than two additions (not including end), otherwise, it will create a room with five (previous room plus the three additions and end mapped by the rule) rooms adjacent to one another, resulting in 1. (see above).

Also, when creating rules, it's good to have some 'end' rules to be non-terminal, just in case the combination would otherwise result in a dead-end. Creating the end to be non-terminal also offers greater novelty/diversity. However, too many of these begin to break the code with larger backbones. Doing this with small backbones (5-15 entries to the list) makes a larger and more complex map, but doing this with large backbones (15-30) can make complex null pointers or simply too many off-branches that result in 1. (see above).

When rule  = GraphRule<ZeldaGrammar>(ZeldaGrammar.TYPE_S)
Feel free to use addNodeToStart more freely than in the case of two non-terminal inputs, simply because there is no 'end' node getting in the way.

Be sure to make rules for every combination! This includes mapping something to itself (rule = new GraphRule<ZeldaGrammar>(ZeldaGrammar.ENEMY_S, ZeldaGrammar.ENEMY_S)). If you don't then it may result in every ENEMY_S mapping to a new TREASURE and make multiple Triforces!

Also, DO NOT have a rule that does not involve RAFT_S or TREASURE map to either. If you do this, then multiple RAFTs and TREASUREs will appear on the map.

**Comment by schrum2** [comment]
Time to resurrect this issue. Because of #484 we can now apply different grammar rules to interactively evolved dungeons. When I run ZeldaGANLevelBreederTask and select certain options, I get the following error:
![image](https://user-images.githubusercontent.com/8397236/82943822-cf7ce600-9f5f-11ea-8f87-0557c0b6fcd6.png)
As you can see in the picture, I selected the Standard Grammar Rules with the Interesting Backbone. Then I selected the rooms in blue: the three at the end of the second row. Posted below is the complete stack track from the error:

```
Placing FAXN at (48, 49) Lock
Placing UVSM at (47, 49) ENEMY
Placing TYFT at (46, 49) SoftLock
Placing INER at (46, 50) Key
Placing CJGN at (46, 48) Enemy
{INER=INER, FAXN=FAXN, CJGN=CJGN, TYFT=TYFT, UVSM=UVSM, PVBT=PVBT}
SET:[INER, FAXN, CJGN, TYFT, UVSM, PVBT]
GET:null
CHECK:false
currentLevel:PVBT
null
Name isn't in list : null
java.lang.NullPointerException
	at edu.southwestern.tasks.gvgai.zelda.level.ZeldaLevelUtil$1.h(ZeldaLevelUtil.java:868)
	at edu.southwestern.tasks.gvgai.zelda.level.ZeldaLevelUtil$1.h(ZeldaLevelUtil.java:1)
	at edu.southwestern.util.search.AStarSearch$1.compare(AStarSearch.java:37)
	at edu.southwestern.util.search.AStarSearch$1.compare(AStarSearch.java:1)
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:670)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:646)
	at java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at java.util.PriorityQueue.add(PriorityQueue.java:322)
	at edu.southwestern.util.search.GraphSearch.search(GraphSearch.java:55)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.DungeonUtil.makeDungeonPlayable(DungeonUtil.java:993)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.GraphDungeon.makeDungeon(GraphDungeon.java:49)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.showDungeon(ZeldaDungeon.java:260)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.respondToClick(ZeldaGANLevelBreederTask.java:381)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.actionPerformed(InteractiveEvolutionTask.java:839)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.getDungeonGrid(ZeldaDungeon.java:444)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.showDungeon(ZeldaDungeon.java:427)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.respondToClick(ZeldaGANLevelBreederTask.java:381)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.actionPerformed(InteractiveEvolutionTask.java:839)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

You should be able to reproduce this error @cappsb which will help you troubleshoot.

**Comment by schrum2** [comment]
Ok, I just made a big change to the Graph class that touches this code. The change is in the `dev` branch. I think everything works as well as it did before, though this reminded me of the lingering problems we have with the graph rule sets. I still want this resolved before SCOPE ends. In particular:

When I use the ZeldaGANLevelBreederTask, I should be able to combine any of the provided Grammar Rules with any of the provided Grammar Backbones. However, combining Standard rules with the Interesting backbone causes this exception (other combinations also fail):

```
Placing JRML at (49, 48) Lock
Placing CBXS at (48, 48) ENEMY
Placing NVLN at (48, 47) SoftLock
Placing UFFB at (47, 47) Key
Placing XREH at (48, 46) Enemy
{XREH=XREH, JRML=JRML, CBXS=CBXS, UFFB=UFFB, NVLN=NVLN, NNJE=NNJE}
SET:[XREH, JRML, CBXS, UFFB, NVLN, NNJE]
GET:null
CHECK:false
currentLevel:NNJE
null
Name isn't in list : null
java.lang.NullPointerException
	at edu.southwestern.tasks.gvgai.zelda.level.ZeldaLevelUtil$2.h(ZeldaLevelUtil.java:868)
	at edu.southwestern.tasks.gvgai.zelda.level.ZeldaLevelUtil$2.h(ZeldaLevelUtil.java:855)
	at edu.southwestern.util.search.AStarSearch$1.compare(AStarSearch.java:37)
	at edu.southwestern.util.search.AStarSearch$1.compare(AStarSearch.java:29)
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:670)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:646)
	at java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at java.util.PriorityQueue.add(PriorityQueue.java:322)
	at edu.southwestern.util.search.GraphSearch.search(GraphSearch.java:55)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.DungeonUtil.makeDungeonPlayable(DungeonUtil.java:993)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.GraphDungeon.makeDungeon(GraphDungeon.java:47)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.showDungeon(ZeldaDungeon.java:260)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.respondToClick(ZeldaGANLevelBreederTask.java:381)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.actionPerformed(InteractiveEvolutionTask.java:839)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.getDungeonGrid(ZeldaDungeon.java:444)
	at edu.southwestern.tasks.gvgai.zelda.dungeon.ZeldaDungeon.showDungeon(ZeldaDungeon.java:427)
	at edu.southwestern.tasks.interactive.gvgai.ZeldaGANLevelBreederTask.respondToClick(ZeldaGANLevelBreederTask.java:381)
	at edu.southwestern.tasks.interactive.InteractiveEvolutionTask.actionPerformed(InteractiveEvolutionTask.java:839)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

If certain backbones are problematic, then you can simply remove them from the menu, but in the end I want to have at least two working backbones and two working rule sets.
@cappsb 

Make a new branch off of `dev` for resolving this.

**Comment by cappsb** [comment]
Buttons are hidden. I do not know why the null pointer happens.
