### ISSUE TITLE
Exception when running MAPElitesZeldaCPPNThenDirect-RoomsTraversed.bat 0

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#489]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
        at java.util.ArrayList.get(ArrayList.java:435)
        at edu.southwestern.tasks.gvgai.zelda.level.ZeldaState.pickupItems(ZeldaState.java:81)
        at edu.southwestern.tasks.gvgai.zelda.level.ZeldaState.<init>(ZeldaState.java:61)
        at edu.southwestern.tasks.gvgai.zelda.level.ZeldaState.getSuccessor(ZeldaState.java:164)
        at edu.southwestern.tasks.gvgai.zelda.level.ZeldaState.getLegalActions(ZeldaState.java:254)
        at edu.southwestern.util.search.State.getSuccessors(State.java:32)
        at edu.southwestern.util.search.GraphSearch.search(GraphSearch.java:46)
        at edu.southwestern.tasks.zelda.ZeldaDungeonTask.evaluate(ZeldaDungeonTask.java:178)
        at edu.southwestern.evolution.mapelites.MAPElites.newIndividual(MAPElites.java:197)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.run(SteadyStateExperiment.java:40)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:910)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1131)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1091)
```

Seems to be a problem with the search, but perhaps it was caused by something else. Sparse keys? Other issue?

**Comment by schrum2** [comment]
This actually seems to be a serious issue that comes up with every run of the batch file made for #477

**Comment by schrum2** [comment]
Shockingly, the CPPNorDirect2GAN approach seems to be generating rooms that are not properly surrounded by walls, but I didn't think the model ever did that. I could simply force surrounding walls in every room, but this error seems so odd that I think some other error must be causing it. I'm going to see if I can figure out why rooms with improper walls are being created, but will simply repair the rooms after generation if necessary.

**Comment by schrum2** [comment]
I believe this is fixed by forcing the presence of walls in the levelGridFromLatentVectorGrid method of the ZeldaCPPNtoGANLevelBreederTask class
