### ISSUE TITLE
Other Scores for num segments not tracked

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#569]
I was running evolution experiments using objective evolution (A* and connectivity) and the scores for num segments of each type (horizontal, up, corner, etc) were all 0. This needs to be fixed, or we need to drop them ... though I worry that this might also be messing up MAP Elites bins (haven't checked yet). Obviously, this was caused by refactoring level generation to unify the OneGAN and SevenGAN approaches, but it needs to be fixed. Hopefully, this can be done in the code shared by all ... in the MegaManGANGenerator class? Not sure.

**Comment by cappsb** [comment]
Scores should be tracked now.

**Comment by schrum2** [comment]
Received exception
```
Exception in thread "main" java.lang.NullPointerException
        at edu.southwestern.tasks.megaman.gan.MegaManGANUtil.findSegmentData(MegaManGANUtil.java:652)
        at edu.southwestern.tasks.megaman.gan.MegaManGANUtil.longVectorToMegaManLevel(MegaManGANUtil.java:627)
        at edu.southwestern.tasks.megaman.MegaManGANLevelTask.getMegaManLevelListRepresentationFromStaticGenotype(MegaManGANLevelTask.java:55)
        at edu.southwestern.tasks.megaman.MegaManGANLevelTask.getMegaManLevelListRepresentationFromGenotype(MegaManGANLevelTask.java:42)
        at edu.southwestern.tasks.megaman.MegaManLevelTask.oneEval(MegaManLevelTask.java:119)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
        at edu.southwestern.evolution.mulambda.MuLambda.processChildren(MuLambda.java:244)
        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:384)
        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:928)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1149)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1109)
```
@cappsb Please Maven build and test run the `MegaManOneGAN-AStarDistAndConnectivity.bat` batch file before asking me to look again.

Also, don't define the exact same findSegmentData method in two distinct places. Make it a public method in some class (make a brand new class for tracking the data and the global variables) and put the method there, where it can be called from any other method.

**Comment by cappsb** [comment]
![image](https://user-images.githubusercontent.com/63438571/87511723-6a7a6e00-c63b-11ea-8de5-023747bf8db5.png)
Take a look

**Comment by schrum2** [comment]
Seems good.
