### ISSUE TITLE
GVG-AI levels: support more games

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#57]
Currently, GVG-AI level evolution only works for zelda and blacksmoke. Support needs to be added for more games, or even better, a general way of supporting all games based on information from the game should be devised. However, this could be quite hard, and may not be worth the effort.

**Comment by schrum2** [comment]
Issues #92 is a specific instance of this issue. Once you complete #92 you can start thinking about this broader issue.

**Comment by JoeRoybal** [comment]
I've been working on making games compatible and have run into some issues. First of all, I need to find a way to make the game size tailored as opposed to general. Would it be alright if I made constants for specific levels; for example, aliens cant start on the same line as the avatar. or would this be going against the spirit of random levels being evolved into something playable?

**Comment by JoeRoybal** [comment]
![alienissue](https://user-images.githubusercontent.com/39634437/40929143-7f37ec80-67e9-11e8-85fb-23e9a1890db4.PNG)

**Comment by JoeRoybal** [comment]
Issue when attempting to play pacman:

```
Exception in thread "Thread-2" java.lang.NullPointerException
	at gvgai.core.game.Game.getPath(Game.java:2164)
	at gvgai.ontology.sprites.npc.PathAltChaser.update(PathAltChaser.java:84)
	at gvgai.ontology.sprites.npc.RandomPathAltChaser.update(RandomPathAltChaser.java:56)
	at gvgai.core.game.ForwardModel.tick(ForwardModel.java:580)
	at gvgai.core.game.ForwardModel.advance(ForwardModel.java:596)
	at gvgai.core.game.StateObservation.advance(StateObservation.java:65)
	at gvgai.tracks.ArcadeMachine.warmUp(ArcadeMachine.java:781)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:106)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:91)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:70)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask$1.run(LevelBreederTask.java:180)
```

**Comment by schrum2** [comment]
In general, please avoid changing the data files that describe the games, unless there is some error with them. I would actually like these files to be changed back, unless there is a compelling reason why you thought they needed to be changed.

**Comment by JoeRoybal** [comment]
"""
Exception in thread "Thread-5" java.lang.NullPointerException
	at gvgai.core.game.Game.getPath(Game.java:2164)
	at gvgai.ontology.sprites.npc.PathAltChaser.update(PathAltChaser.java:84)
	at gvgai.core.game.ForwardModel.tick(ForwardModel.java:580)
	at gvgai.core.game.ForwardModel.advance(ForwardModel.java:596)
	at gvgai.core.game.StateObservation.advance(StateObservation.java:65)
	at gvgai.tracks.ArcadeMachine.warmUp(ArcadeMachine.java:757)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:106)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:91)
	at edu.southwestern.tasks.gvgai.GVGAIUtil.runOneGame(GVGAIUtil.java:70)
	at edu.southwestern.tasks.interactive.gvgai.LevelBreederTask$1.run(LevelBreederTask.java:351)
"""

**Comment by schrum2** [comment]
How many games are left? Do you think you'll be done tomorrow? The next day? When you are finished, please make a list in this issue thread of all the games that can evolve semi-playable levels, and a separate list of the ones that play really broken levels, and then maybe a final list of games that simply do not work (crash)

**Comment by JoeRoybal** [comment]
I should be done today or really close going at my current speed. I will work on the list right after the final levels are supported.

**Comment by JoeRoybal** [comment]
Semi-Playable: Zelda, blacksmoke, chipschallenge,  pacman, avoidgeorge, bait, boloadventures, bomber, bomberman, boulderchase, boulderdash, brainman, butterflies, cakybaky, chase, clusters, cookmepasta, crossfire, defem, eggomania, escape, fireman, garbagecollector, hungrybirds, iceandfire, infection, jaws, lasers, lasers2, lemmings, misslecommand, overload, painter, pokemon, wrapsokoban, zenpuzzle, realsokoban, rivers, run, seaquest, sokoban, superman, surround, survivezombies, thesnowman, thecitadel, whackamole, watergame

**Comment by JoeRoybal** [comment]
Broken: aliens, angelsdemons, assemblyline, beltmanager, catapults, portals, colourscape, cops, dungeon, eigthpassenger, enemycitadel, factorymanager, firecaster, firestorms, freeway, frogs, gymkhana, intersection, islands, killbillvol1, labyrinth, labyrinthdual, modality, plants, plaqueattack, witnessprotection, realportals, roadfighter, roguelike, sheriff, shipwreck, solarfox, tercio, waves, wildgunman

**Comment by JoeRoybal** [comment]
Does Not Work: camelrace, chainreaction, chopper, myAliens, racebet, racebet2, waitforbreakfast

**Comment by JoeRoybal** [comment]
All games now have support
