### ISSUE TITLE
Exit item inaccessible

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#575]
Since we evolve with A* and connectivity, every run has 2 champions ... one for each objective. The connectivity champion for seven GAN with seed 0 has a problem:

![image](https://user-images.githubusercontent.com/8397236/87865664-bda33800-c93d-11ea-872b-29055c443748.png)

The exit item at the end is inaccessible because it is recessed in the wall.

This can be fixed in a number of ways. Perhaps the best: when a candidate location is chosen for the exit item, just make sure there is an empty space above the location you want to place it ... otherwise, generate a new candidate location.

**Comment by cappsb** [comment]
Last commit should have fixed this (see #574 commit, forgot to tag).

**Comment by schrum2** [comment]
This is causing an exception:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
        at java.util.ArrayList.get(ArrayList.java:435)
        at edu.southwestern.tasks.megaman.gan.MegaManGANUtil.placeOrb(MegaManGANUtil.java:467)
        at edu.southwestern.tasks.megaman.gan.MegaManGANUtil.longVectorToMegaManLevel(MegaManGANUtil.java:623)
        at edu.southwestern.tasks.megaman.MegaManGANLevelTask.getMegaManLevelListRepresentationFromStaticGenotype(MegaManGANLevelTask.java:61)
        at edu.southwestern.tasks.megaman.MegaManGANLevelTask.getMegaManLevelListRepresentationFromGenotype(MegaManGANLevelTask.java:48)
        at edu.southwestern.tasks.megaman.MegaManLevelTask.oneEval(MegaManLevelTask.java:119)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:104)
        at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:93)
        at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:209)
        at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:363)
        at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:928)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1149)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1109)
```

**Comment by schrum2** [comment]
I think you fixed the placement, but this makes me realize that the real problem is that the A* model thought it was possible to grab that item in the first place ... it is not. See #570 for an update on this.
