### ISSUE TITLE
Innovation Engine can't get DL4J model Zoo models anymore

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#583]
The Innovation Engine uses pre-trained CNNs from DL4J's model zoo, but apparently at some point (I know they have gone through a few upgrades) they made it impossible to download these models using the old code.

Do I want to go through the effort to get this ability back, or do I just take this chance to wipe out DL4J from MM-NEAT entirely?

**Comment by schrum2** [comment]
If I tackle this problem then I'll probably need to use information from here:
https://deeplearning4j.konduit.ai/model-zoo/overview

**Comment by schrum2** [comment]
I tried changing the DL4J version to 1.0.0-beta6. I had to remove deeplearning4j-modelimport. This also produced syntax errors in TensorNetworkFromHyperNEATSpecification. However, even after commenting them out, some new problem emerged in the innovation engine:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/schrum2/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/schrum2/.m2/repository/org/slf4j/slf4j-simple/1.5.8/slf4j-simple-1.5.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:75)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:56)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:43)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:28)
	at edu.southwestern.MMNEAT.MMNEAT.loadClasses(MMNEAT.java:640)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:759)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:986)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:946)
	at edu.southwestern.tasks.innovationengines.PictureInnovationTask.main(PictureInnovationTask.java:133)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.md5Hex(Ljava/io/InputStream;)Ljava/lang/String;
	at org.nd4j.resources.Downloader.checkMD5OfFile(Downloader.java:120)
	at org.nd4j.resources.Downloader.download(Downloader.java:58)
	at org.nd4j.resources.Downloader.download(Downloader.java:50)
	at org.deeplearning4j.zoo.util.BaseLabels.getResourceFile(BaseLabels.java:159)
	at org.deeplearning4j.zoo.util.imagenet.ImageNetLabels.getLabels(ImageNetLabels.java:49)
	at org.deeplearning4j.zoo.util.BaseLabels.<init>(BaseLabels.java:43)
	at org.deeplearning4j.zoo.util.imagenet.ImageNetLabels.<init>(ImageNetLabels.java:43)
	at edu.southwestern.util.graphics.AccessibleImageNetLabels.<init>(AccessibleImageNetLabels.java:16)
	at edu.southwestern.util.graphics.ImageNetClassification.getImageNetLabelsInstance(ImageNetClassification.java:38)
	at edu.southwestern.util.graphics.ImageNetClassification.getImageNetLabels(ImageNetClassification.java:54)
	at edu.southwestern.tasks.innovationengines.ImageNetBinMapping.binLabels(ImageNetBinMapping.java:19)
	at edu.southwestern.evolution.mapelites.Archive.<init>(Archive.java:37)
	at edu.southwestern.evolution.mapelites.MAPElites.<init>(MAPElites.java:65)
	... 13 more
```
I did not commit any changes as a result. Will require more analysys

**Comment by schrum2** [comment]
There were conflicting versions of the commons-codec libraries in the Maven pom, so I removed that and it fixed the final problems with the Innovation Engine
