### ISSUE TITLE
Fix Neural Style Transfer in Python

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#613]
The PictureStyleBreederTask tries to launch the Python version of Neural Style Transfer which no longer works for some reason. I think this is an issue specific to one machine, and is related to the Python libraries on the system. However, it would be nice if the code clarified how to make this work. The specific error is:
```
Traceback (most recent call last):
  File ".\src\main\python\NeuralStyleTransfer\neural_style_json.py", line 5, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by schrum2** [comment]
Working with this more, it is clear that as newer versions of the Python libraries associated with this code have come out, the old code is no longer able to work. So, the only way to get the code to work would be to figure out the precise older versions of the libraries that need to be used. However, I don't think it is worth the hassle.
