### ISSUE TITLE
Problem finding randomOccupiedBinIndex with CMA-ME

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#696]
When I tried running CMA-ME with 15 emitters on Rastrigen, I got this error:

```
Constructor: public edu.southwestern.experiment.evolution.SteadyStateExperiment()
(25,50)-CMA-ES(mu_eff=14.2), Ver="0.99.40", dimension=20, 0 diagonal iter., randomSeed=1623811157979 (Tue Jun 15 21:39:18 CDT 2021)
ImprovementEmitter1 allows raw logging
(25,50)-CMA-ES(mu_eff=14.2), Ver="0.99.40", dimension=20, 0 diagonal iter., randomSeed=1623811158072 (Tue Jun 15 21:39:18 CDT 2021)
ImprovementEmitter2 allows raw logging
(25,50)-CMA-ES(mu_eff=14.2), Ver="0.99.40", dimension=20, 0 diagonal iter., randomSeed=1623811158085 (Tue Jun 15 21:39:18 CDT 2021)
ImprovementEmitter3 allows raw logging
(25,50)-CMA-ES(mu_eff=14.2), Ver="0.99.40", dimension=20, 0 diagonal iter., randomSeed=1623811158097 (Tue Jun 15 21:39:18 CDT 2021)
ImprovementEmitter4 allows raw logging
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:75)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:56)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:43)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:28)
	at edu.southwestern.MMNEAT.MMNEAT.loadClasses(MMNEAT.java:739)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:827)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1060)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1020)
Caused by: java.lang.IllegalStateException: The number of occupied bins (50) and the archive size (250000) have a problem. 4 steps left out of 49. occupiedCount = 45
	at edu.southwestern.evolution.mapelites.Archive.randomOccupiedBinIndex(Archive.java:270)
	at edu.southwestern.evolution.mapelites.emitters.Emitter.newCMAESInstance(Emitter.java:69)
	at edu.southwestern.evolution.mapelites.emitters.Emitter.<init>(Emitter.java:39)
	at edu.southwestern.evolution.mapelites.emitters.ImprovementEmitter.<init>(ImprovementEmitter.java:11)
	at edu.southwestern.evolution.mapelites.CMAME.initialize(CMAME.java:54)
	at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:26)
	at edu.southwestern.experiment.evolution.SteadyStateExperiment.<init>(SteadyStateExperiment.java:21)
```

I wonder if this could explain some of our problems. This seems to indicate that we might somehow be tracking the `occupiedBins` incorrectly, which would make our results look bad. Then again, maybe this is just some other error. It should be investigates either way.

**Comment by schrum2** [comment]
Note: This error occurred in my `schrum_dev` branch (and re-occurred when I tried to run again), but I launched in `dev_maxx` with the same commend (same random seed) and it is now running. I'll let it run over night, and try to diagnose the problems with my own branch myself.

**Comment by schrum2** [comment]
Once I knew this was just a problem with my branch, I was able to trace it back to newly added code for parallelizing the initialization of the MAP-Elites archive. The code lacked proper synchronization.

The bug is fixed now, so I'll close the issue, but this makes me a bit warry about adding more parallelization ... it's so easy for errors to creep in.
