### ISSUE TITLE
Crash With Mario KL Div

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#726]
Running `MarioMAPElites-KLDivergence-ME.bat 64`

Following exception
```
Exception in thread "main" java.lang.IllegalStateException: 0.3025095883330894 exceeds maximum value specified (0.3)
        at edu.southwestern.evolution.mapelites.generalmappings.MultiDimensionalRealValuedBinLabels.discretize(MultiDimensionalRealValuedBinLabels.java:121)
        at edu.southwestern.evolution.mapelites.generalmappings.KLDivergenceBinLabels.multiDimensionalIndices(KLDivergenceBinLabels.java:77)
        at edu.southwestern.evolution.mapelites.BaseBinLabels.oneDimensionalIndex(BaseBinLabels.java:16)
        at edu.southwestern.tasks.mario.MarioLevelTask.oneEval(MarioLevelTask.java:493)
        at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:126)
        at edu.southwestern.evolution.mapelites.MAPElites.newIndividual(MAPElites.java:512)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment.run(SteadyStateExperiment.java:44)
        at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:832)
        at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:1061)
        at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:1021)
Traceback (most recent call last):
  File ".\src\main\python\GAN\generator_ws.py", line 145, in <module>
    lv = numpy.array(json.loads(line))
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Last bit of text from program:
```
Save image: mariolevelskldivergence/ME64\archive\0_219to0_222-0_066to0_069_359.00000_48835.png
Saved object to mariolevelskldivergence/ME64\archive\0_219to0_222-0_066to0_069-elite.xml
48737   0
14 : 280
N Dims = 3920
205
14 : 350
N Dims = 4900
171
14 : 280
N Dims = 3920
205
14 : 174
N Dims = 2436
200
```

**Comment by MBatt1** [comment]
The KL Div limit is defined in the batch file, and should be as close as possible to the limit, but we really don't know how well it will do until we test it, so it just needs to be increased int he batch files, 0.35 probably will work

**Comment by schrum2** [comment]
I don't think the KL Div binning scheme is compelling enough to spend a lot of time correcting this, but what I would like you to do before closing this issue is replace this confusing exception with a very precise error message that suggests to the user of the program which command line parameter to change, and in which way (increase vs decrease).

**Comment by MBatt1** [comment]
Now tells user to increase the klDivMaxValue parameter, and I've fixed the other batch files to have the correct max value
