### ISSUE TITLE
MarioCPPNLevelTask crashes after a single level evaluation

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#743]
Although I'm not really using this for any active experiments, it bothers me that this does not work. Clearly, all of the extensive work on Mario GAN and CPPN2GAN, etc changed something about how Mario levels are evaluated that makes this not work. Basically, a level is generated just fine, and with watch:true the evaluation is shown, but then the code crashes because the length of the level is not properly divisible by some kind of segment length. Specifically, here is the stack trace:
```
getLevelStats: Level not multiple of segment width
Exception in thread "main" java.lang.NullPointerException
	at edu.southwestern.tasks.mario.MarioLevelTask.evaluateOneLevel(MarioLevelTask.java:309)
	at edu.southwestern.tasks.mario.MarioLevelTask.oneEval(MarioLevelTask.java:256)
	at edu.southwestern.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:126)
	at edu.southwestern.tasks.LonerTask$EvaluationThread.call(LonerTask.java:91)
	at edu.southwestern.tasks.LonerTask.evaluateAll(LonerTask.java:207)
	at edu.southwestern.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:383)
	at edu.southwestern.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:216)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:533)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:762)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:722)
	at edu.southwestern.tasks.mario.MarioCPPNLevelTask.main(MarioCPPNLevelTask.java:58)
```

One possibility that occurs to me is that the pure CPPN levels were never meant to be evaluated the way the Mario GAN levels are, since they do not actually consist of segments. One approach is to disable segment-based fitness on the CPPN levels. Another is to simply switch the CPPN level size to be properly divisible by the segment length, but this would limit the length of levels that could be produced.

I think that segment-based fitness should be conditional, or at least not crash evaluation as long as other fitness functions are available.

**Comment by schrum2** [comment]
I made the code in the MarioTask simply ignore the bad null values when they cannot be generated (due to CPPNs not caring about segments). As long as the fitness functions or behavior characterizations depending on segments are not used (parameters set to false), then the code runs fine as normal. I was able to run MarioCPPNLevelTask successfully for many generations. I also ran some Mario GAN experiments that depend on the segment calculations to make sure nothing broke there. This seems to all work, so I'm closing the issue.
