### ISSUE TITLE
PictureInnovationTask OutOfMemory error

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#753]
Haven't run this in a while, but when I do I get an OutOfMemoryError. I was on the verge of removing all DL4J code from MM-NEAT, and this bit of code is one of the few reasons I would consider keeping DL4J around. If I can't get this to work, then I might as well remove DL4J all together.

Here is the stack trace:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:75)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:56)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:43)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:28)
	at edu.southwestern.util.graphics.ImageNetClassification.initImageNet(ImageNetClassification.java:89)
	at edu.southwestern.util.graphics.ImageNetClassification.getChosenImageNetModel(ImageNetClassification.java:68)
	at edu.southwestern.util.graphics.ImageNetClassification.getImageNetPredictions(ImageNetClassification.java:152)
	at edu.southwestern.tasks.innovationengines.PictureInnovationTask.evaluate(PictureInnovationTask.java:59)
	at edu.southwestern.evolution.mapelites.MAPElites.lambda$initialize$0(MAPElites.java:341)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
	at org.deeplearning4j.util.ModelSerializer.loadZipData(ModelSerializer.java:990)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:470)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:463)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:648)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:604)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:101)
	at edu.southwestern.networks.dl4j.ZooModelImageNetWrapper.<init>(ZooModelImageNetWrapper.java:23)
	at edu.southwestern.networks.dl4j.VGG16Wrapper.<init>(VGG16Wrapper.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:75)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:56)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:43)
	at edu.southwestern.util.ClassCreation.createObject(ClassCreation.java:28)
	at edu.southwestern.util.graphics.ImageNetClassification.initImageNet(ImageNetClassification.java:89)
	at edu.southwestern.util.graphics.ImageNetClassification.getChosenImageNetModel(ImageNetClassification.java:68)
	at edu.southwestern.util.graphics.ImageNetClassification.getImageNetPredictions(ImageNetClassification.java:152)
	at edu.southwestern.tasks.innovationengines.PictureInnovationTask.evaluate(PictureInnovationTask.java:59)
	at edu.southwestern.evolution.mapelites.MAPElites.lambda$initialize$0(MAPElites.java:341)
	at edu.southwestern.evolution.mapelites.MAPElites$$Lambda$1/158453976.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
java.lang.reflect.InvocationTargetException
```

**Comment by schrum2** [comment]
This is solved. Some MAP Elites optimizations (parallelization) didn't work with this task since the memory of evaluating a single image is so high (because of the NN). It works again, so I guess I'll keep DL4J for a little while at least.
