### ISSUE TITLE
Minecraft batch files with CMA-ME

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#831]
Whatever is in the Experiments-2022-MinecraftFlyingMachines directory should also have a version that uses CMA-ME instead of regular MAP Elites

**Comment by schrum2** [comment]
First test file seemed to overwhelm the server. Need to try again to check

**Comment by schrum2** [comment]
Test run crashed with this stack trace:
```
 CMA-ES error: updateDistribution() was already called
Exception in thread "Thread-11" fr.inria.optimization.cmaes.CMAEvolutionStrategy$CMAException:  CMA-ES error: updateDistribution() was already called
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.error(CMAEvolutionStrategy.java:873)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.updateDistribution(CMAEvolutionStrategy.java:1658)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.updateDistribution(CMAEvolutionStrategy.java:1647)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.updateDistribution(CMAEvolutionStrategy.java:1616)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.updateDistribution(Emitter.java:127)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.addFitness(Emitter.java:174)
        at edu.southwestern.evolution.mapelites.CMAME.newIndividual(CMAME.java:130)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment$1.run(SteadyStateExperiment.java:51)
```
Might be related to the weird style of multithreading and lack of synchronization on CMA-ME

**Comment by schrum2** [comment]
Will need to fix this later, but here is my hypothesis about the error.

CMA-ME should not generate a new individual from the current emitter if `additionCounter == populationSize` already. However, fixing this means I'll need to add a lot of synchronized checks to assure that an emitter that is about to be maxed out is not chosen to produce yet another individual

**Comment by schrum2** [comment]
Used a semaphore to control the right to produce a new individual with each emitter.

Seems to work, so only step left is to make all the batch files.

**Comment by schrum2** [comment]
I thought the semaphore solved my problems, but now I'm getting this error:
```
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: 192
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.tql2(CMAEvolutionStrategy.java:1344)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.eigendecomposition(CMAEvolutionStrategy.java:1100)
        at fr.inria.optimization.cmaes.CMAEvolutionStrategy.samplePopulation(CMAEvolutionStrategy.java:1486)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.samplePopulation(Emitter.java:215)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.resetSample(Emitter.java:229)
        at edu.southwestern.evolution.mapelites.emitters.Emitter.sampleSingle(Emitter.java:242)
        at edu.southwestern.evolution.mapelites.CMAME.newIndividual(CMAME.java:115)
        at edu.southwestern.experiment.evolution.SteadyStateExperiment$1.run(SteadyStateExperiment.java:51)
```

I'm going to add some additional synchronization, but I'm not sure that will be enough.

**Comment by schrum2** [comment]
An overnight run is still going without crashing, so I guess the synchronization worked. However, I wonder if I've made things a lot slower than they should be. Also, not having great success with CMA-ME on the count/negative binning scheme, but I sort of wonder if that is actually because the shape size is 4x4x4. Although we had success with this binning scheme for smaller shapes, it doesn't seem to work well with 4x4x4.

I'll let it run a bit longer. Even if the results don't look good, I should test out other binning schemes with more batch files. They can be in an aux dir rather than the main dir if they don't work well.

**Comment by schrum2** [comment]
The results just don't look that good. I'll keep the one batch file around, but I don't think it's worth doing the others.
