### ISSUE TITLE
Redstone vs Piston run almost finished, then crashed

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#840]
Here is a stack trace
```
Traceback (most recent call last):
  File ".\src\main\python\EvoCraft\ServerSendReceive.py", line 56, in <module>
    result = client.readCube(Cube(min=Point(x=xmin, y=ymin, z=zmin), max=Point(x=xmax, y=ymax, z=zmax) ))
  File "C:\Users\he_de.000\AppData\Roaming\Python\Python37\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\he_de.000\AppData\Roaming\Python\Python37\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "{"created":"@1658059000.040000000","description":"Error received from peer ipv6:[::1]:5001","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Stream removed","grpc_status":2}"
>
[ERROR] processCommRecv: Null message.
Python process for interacting with the Minecraft server is not responding.
This likely means the Minecraft server was overwhelmed. Try increasing the "minecraftClearSleepTimer"
Exception in thread "Thread-8" java.lang.NullPointerException: Response not received from readCube. Server is probably overwhelmed and crashed.
```

**Comment by schrum2** [comment]
Doesn't seem to be a recurring error, though it also happened with a binning scheme that we are not really using. However, some new binning schemes are being built on top of this, and don't seem to have problems yet, so I'm closing this issue until we see evidence that it needs to be addressed.
