### ISSUE TITLE
Server Crashes for Long Missile Runs

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEAT#883]
At least two distinct directed missile runs crashed because the server was overwhelmed:
```
Traceback (most recent call last):
  File ".\src\main\python\EvoCraft\ServerSendReceive.py", line 84, in <module>
    client.fillCube(FillCubeRequest(cube=Cube(min=Point(x=xmin, y=ymin, z=zmin), max=Point(x=xmax, y=ymax, z=zmax) ), type=type ))
  File "C:\Python37\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Python37\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:5001 {created_time:"2023-05-31T10:52:51.484028524+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>
[ERROR] processCommRecv: Null message.
Python process for interacting with the Minecraft server is not responding.
This likely means the Minecraft server was overwhelmed. Try increasing the "minecraftClearSleepTimer"
Exception in thread "Thread-7" [ERROR] processCommRecv: Null message.
Python process for interacting with the Minecraft server is not responding.
This likely means the Minecraft server was overwhelmed. Try increasing the "minecraftClearSleepTimer"
Exception in thread "Thread-8" [ERROR] processCommRecv: Null message.
Python process for interacting with the Minecraft server is not responding.
This likely means the Minecraft server was overwhelmed. Try increasing the "minecraftClearSleepTimer"
java.lang.NullPointerException: Response not received from readCube. Server is probably overwhelmed and crashed.[ERROR] 
```

**Comment by schrum2** [comment]
This hasn't occurred again, so I'm closing the issue
